/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Chris' at '5/9/17 8:51 AM' with Gradle 2.14.1
 *
 * @author Chris, @date 5/9/17 8:51 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
